export const APP_CONSTANT = {
  IDLE: "IDLE",
  INTRO: "INTRO",
  ASKING: "ASKING",
  REPLAYING: "REPLAYING",
  LISTENING: "LISTENING",
  SUBMITTING: "SUBMITTING",
  ENDING: "ENDING",
  COMPLETED: "COMPLETED",
};
